<?php

namespace Database\Seeders;

use App\Models\Siswa;
use Illuminate\Support\Str;
use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use PhpOffice\PhpSpreadsheet\IOFactory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SiswaSeeder extends Seeder
{
    public function run(): void
    {
        $filePath = storage_path('app/public/seeder/data_siswa.xlsx');

        $spreadsheet = IOFactory::load($filePath);
        $worksheet = $spreadsheet->getActiveSheet();
        $rows = $worksheet->toArray(null, true, true, true);

        foreach (array_slice($rows, 1) as $row) {
            if (empty($row['A'])) {
                continue;
            }
            Siswa::create([
                'nama'            => $row['A'] ? Str::title(strtolower($row['A'])) : null,
                'nis'             => $row['B'],
                'nisn'            => $row['C'],
                'tempat_lahir'    => $row['D'] ? Str::title(strtolower($row['D'])) : null,
                'tanggal_lahir' => !empty($row['E'])
                    ? Carbon::parse($row['E'])->format('Y-m-d')
                    : null,
                'jenis_kelamin'   => $row['F'] == 'L' ? 'Laki-laki' : 'Perempuan',
                'agama'           => $row['G'] ?? null,
                'sekolah_asal'    => $row['H'] ?? null,
                'alamat'          => $row['I'] ?? null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ]);
        }
    }
    // public function run(): void
    // {
    //     Siswa::insert([
    //         [
    //             'nama' => 'Ahmad',
    //             'nis' => '220001',
    //             'nisn' => '990001',
    //             'tempat_lahir' => 'Jakarta',
    //             'tanggal_lahir' => '2014-01-15',
    //             'jenis_kelamin' => 'Laki-laki',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Bintang Kecil',
    //             'alamat' => 'Jl. Merdeka No. 1',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Rina',
    //             'nis' => '220002',
    //             'nisn' => '990002',
    //             'tempat_lahir' => 'Bandung',
    //             'tanggal_lahir' => '2014-02-20',
    //             'jenis_kelamin' => 'Perempuan',
    //             'agama' => 'Kristen',
    //             'sekolah_asal' => 'TK Harapan',
    //             'alamat' => 'Jl. Sudirman No. 10',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Bagus',
    //             'nis' => '220003',
    //             'nisn' => '990003',
    //             'tempat_lahir' => 'Surabaya',
    //             'tanggal_lahir' => '2014-03-25',
    //             'jenis_kelamin' => 'Laki-laki',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Melati',
    //             'alamat' => 'Jl. Diponegoro No. 5',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Citra',
    //             'nis' => '220004',
    //             'nisn' => '990004',
    //             'tempat_lahir' => 'Yogyakarta',
    //             'tanggal_lahir' => '2014-04-30',
    //             'jenis_kelamin' => 'Perempuan',
    //             'agama' => 'Hindu',
    //             'sekolah_asal' => 'SDN 1 Yogyakarta',
    //             'alamat' => 'Jl. Malioboro No. 8',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Dina',
    //             'nis' => '220005',
    //             'nisn' => '990005',
    //             'tempat_lahir' => 'Medan',
    //             'tanggal_lahir' => '2014-05-10',
    //             'jenis_kelamin' => 'Perempuan',
    //             'agama' => 'Budha',
    //             'sekolah_asal' => 'SDN 3 Medan',
    //             'alamat' => 'Jl. Gatot Subroto No. 12',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Eko',
    //             'nis' => '220006',
    //             'nisn' => '990006',
    //             'tempat_lahir' => 'Semarang',
    //             'tanggal_lahir' => '2014-06-15',
    //             'jenis_kelamin' => 'Laki-laki',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'SDN 2 Semarang',
    //             'alamat' => 'Jl. Pahlawan No. 3',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         // Kelas 2
    //         [
    //             'nama' => 'Budi',
    //             'nis' => '220007',
    //             'nisn' => '990007',
    //             'tempat_lahir' => 'Bandung',
    //             'tanggal_lahir' => '2014-03-10',
    //             'jenis_kelamin' => 'Laki-laki',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Pelangi',
    //             'alamat' => 'Jl. Anggrek No. 2',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Citra',
    //             'nis' => '220008',
    //             'nisn' => '990008',
    //             'tempat_lahir' => 'Jakarta',
    //             'tanggal_lahir' => '2014-05-12',
    //             'jenis_kelamin' => 'Perempuan',
    //             'agama' => 'Kristen',
    //             'sekolah_asal' => 'TK Mawar',
    //             'alamat' => 'Jl. Melati No. 3',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Dimas',
    //             'nis' => '220009',
    //             'nisn' => '990009',
    //             'tempat_lahir' => 'Surabaya',
    //             'tanggal_lahir' => '2014-07-20',
    //             'jenis_kelamin' => 'Laki-laki',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Ceria',
    //             'alamat' => 'Jl. Kenanga No. 4',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Elisa',
    //             'nis' => '220010',
    //             'nisn' => '990010',
    //             'tempat_lahir' => 'Yogyakarta',
    //             'tanggal_lahir' => '2014-09-11',
    //             'jenis_kelamin' => 'Perempuan',
    //             'agama' => 'Katolik',
    //             'sekolah_asal' => 'TK Bintang',
    //             'alamat' => 'Jl. Mawar No. 5',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Fajar',
    //             'nis' => '220011',
    //             'nisn' => '990011',
    //             'tempat_lahir' => 'Semarang',
    //             'tanggal_lahir' => '2014-11-02',
    //             'jenis_kelamin' => 'Laki-laki',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Teratai',
    //             'alamat' => 'Jl. Anggrek No. 6',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Gina',
    //             'nis' => '220012',
    //             'nisn' => '990012',
    //             'tempat_lahir' => 'Bekasi',
    //             'tanggal_lahir' => '2014-12-19',
    //             'jenis_kelamin' => 'Perempuan',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Pelita',
    //             'alamat' => 'Jl. Kamboja No. 7',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],

    //         // Kelas 3
    //         [
    //             'nama' => 'Hendra',
    //             'nis' => '220013',
    //             'nisn' => '990013',
    //             'tempat_lahir' => 'Jakarta',
    //             'tanggal_lahir' => '2013-01-05',
    //             'jenis_kelamin' => 'Laki-laki',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Cerah',
    //             'alamat' => 'Jl. Sakura No. 8',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Indah',
    //             'nis' => '220014',
    //             'nisn' => '990014',
    //             'tempat_lahir' => 'Bogor',
    //             'tanggal_lahir' => '2013-03-21',
    //             'jenis_kelamin' => 'Perempuan',
    //             'agama' => 'Kristen',
    //             'sekolah_asal' => 'TK Mentari',
    //             'alamat' => 'Jl. Mawar No. 9',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Joko',
    //             'nis' => '220015',
    //             'nisn' => '990015',
    //             'tempat_lahir' => 'Depok',
    //             'tanggal_lahir' => '2013-04-18',
    //             'jenis_kelamin' => 'Laki-laki',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Pelita Hati',
    //             'alamat' => 'Jl. Kenanga No. 10',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Kartika',
    //             'nis' => '220016',
    //             'nisn' => '990016',
    //             'tempat_lahir' => 'Yogyakarta',
    //             'tanggal_lahir' => '2013-06-14',
    //             'jenis_kelamin' => 'Perempuan',
    //             'agama' => 'Hindu',
    //             'sekolah_asal' => 'TK Cemerlang',
    //             'alamat' => 'Jl. Dahlia No. 11',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Lukman',
    //             'nis' => '220017',
    //             'nisn' => '990017',
    //             'tempat_lahir' => 'Jakarta',
    //             'tanggal_lahir' => '2013-08-07',
    //             'jenis_kelamin' => 'Laki-laki',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Harapan',
    //             'alamat' => 'Jl. Melati No. 12',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Maya',
    //             'nis' => '220018',
    //             'nisn' => '990018',
    //             'tempat_lahir' => 'Surabaya',
    //             'tanggal_lahir' => '2013-10-09',
    //             'jenis_kelamin' => 'Perempuan',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Cerdas',
    //             'alamat' => 'Jl. Kamboja No. 13',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],

    //         // Kelas 4
    //         [
    //             'nama' => 'Nanda',
    //             'nis' => '220019',
    //             'nisn' => '990019',
    //             'tempat_lahir' => 'Bandung',
    //             'tanggal_lahir' => '2012-02-22',
    //             'jenis_kelamin' => 'Laki-laki',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Ceria',
    //             'alamat' => 'Jl. Mawar No. 14',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Olivia',
    //             'nis' => '220020',
    //             'nisn' => '990020',
    //             'tempat_lahir' => 'Jakarta',
    //             'tanggal_lahir' => '2012-04-01',
    //             'jenis_kelamin' => 'Perempuan',
    //             'agama' => 'Katolik',
    //             'sekolah_asal' => 'TK Mentari',
    //             'alamat' => 'Jl. Anggrek No. 15',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Prasetyo',
    //             'nis' => '220021',
    //             'nisn' => '990021',
    //             'tempat_lahir' => 'Semarang',
    //             'tanggal_lahir' => '2012-05-16',
    //             'jenis_kelamin' => 'Laki-laki',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Harapan',
    //             'alamat' => 'Jl. Dahlia No. 16',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Qirana',
    //             'nis' => '220022',
    //             'nisn' => '990022',
    //             'tempat_lahir' => 'Yogyakarta',
    //             'tanggal_lahir' => '2012-07-25',
    //             'jenis_kelamin' => 'Perempuan',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Pelita',
    //             'alamat' => 'Jl. Sakura No. 17',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Rafi',
    //             'nis' => '220023',
    //             'nisn' => '990023',
    //             'tempat_lahir' => 'Bekasi',
    //             'tanggal_lahir' => '2012-09-30',
    //             'jenis_kelamin' => 'Laki-laki',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Cerah',
    //             'alamat' => 'Jl. Kenanga No. 18',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //         [
    //             'nama' => 'Sinta',
    //             'nis' => '220024',
    //             'nisn' => '990024',
    //             'tempat_lahir' => 'Depok',
    //             'tanggal_lahir' => '2012-11-17',
    //             'jenis_kelamin' => 'Perempuan',
    //             'agama' => 'Islam',
    //             'sekolah_asal' => 'TK Bintang',
    //             'alamat' => 'Jl. Melati No. 19',
    //             'created_at' => now(),
    //             'updated_at' => now(),
    //         ],
    //     ]);
    // }
}
